### ISSUE TITLE
SLES Support

### ISSUE THREAD

**Issue by poikilotherm** [razorsedge/puppet-vmwaretools#16]
Hi there,

I would like to extend the code for some SLES specific stuff, as we use a lot of SLES server VMs. 

As on SLES there is "zypper" as the default and only supported tool, I would like to extend the code to use the zypprepo type created by Darin (https://forge.puppetlabs.com/darin/zypprepo), which was not included into core puppet but published as a module (see Feature #11864 http://projects.puppetlabs.com/issues/11864).
Of course this adds a dependency to this module, but it would be really nice to have a real zypper repo.

Kind regards, Poikilotherm

**Comment by razorsedge** [comment]
Merged in SLES support in commit aae2614478b4ba9a6739a6cac97e4f31b874822d.

**Comment by razorsedge** [comment]
Released to the Forge as version [4.9.0](https://forge.puppetlabs.com/razorsedge/vmwaretools/4.9.0).
