### ISSUE TITLE
rhel_upstart incorrectly set by tools_version "5.5p02"

### ISSUE THREAD

**Issue by dfwarden** [razorsedge/puppet-vmwaretools#26]
With tools_version set to "5.5p02", the regex on line https://github.com/razorsedge/puppet-vmwaretools/blob/master/manifests/init.pp#L192 that is intended to match tools version 5.0 will match "5p0" and incorrectly set rhel_upstart to false. This could be fixed by either escaping the period in 5.0 (so it matches the period character) or by prefixing the regex with the ^ character such that the match can only happen at the beginning of the string. Lost a few hairs to this one before I realized what was happening!

**Comment by razorsedge** [comment]
Fixed in [razorsedge/vmwaretools](https://forge.puppetlabs.com/razorsedge/vmwaretools/) version 4.8.1.
