### ISSUE TITLE
RHEL/Centos 7 Support

### ISSUE THREAD

**Issue by davideagle** [razorsedge/puppet-vmwaretools#28]
Do you have plans to add support for RHEL/Centos 7?

I might be interested in providing a PR in the near future if you'd be willing to accept such an addition

**Comment by razorsedge** [comment]
I do not as VMware is not supporting those platforms with vmwaretools.  
From the README.md Notes:
Not supported on RHEL/CentOS/OEL 7+ or SLES 12 as VMware is recommending [open-vm-tools](http://kb.vmware.com/kb/2073803) instead.

I am considering making an open-vm-tools module, but do not have a timeline.

**Comment by razorsedge** [comment]
I now have an [open-vm-tools](https://forge.puppetlabs.com/razorsedge/openvmtools) module available on the Forge.

**Comment by davideagle** [comment]
Thanks, I'll look into that
