### ISSUE TITLE
Service error on Ubuntu 14.04

### ISSUE THREAD

**Issue by bshow80** [razorsedge/puppet-vmwaretools#29]
I receive this error every time I run "puppet agent --test" and the open-vm-tools service is running already.

Error: Could not start Service[open-vm-tools]: Execution of '/etc/init.d/open-vm-tools start' returned 1: * Starting open-vm daemon vmtoolsd
Error: /Stage[main]/Openvmtools/Service[open-vm-tools]/ensure: change from stopped to running failed: Could not start Service[open-vm-tools]: Execution of '/etc/init.d/open-vm-tools start' returned 1: * Starting open-vm daemon vmtoolsd

**Comment by razorsedge** [comment]
Is this with razorsedge-vmwaretools or razorsedge-openvmtools?

**Comment by bshow80** [comment]
I am using razorsedge-openvmtools. Should I be using the other?

**Comment by razorsedge** [comment]
I was just wondering why you were asking about the open-vm-tools on the vmwaretools issue tracker. :-)  Could you open the issue [over there](https://github.com/razorsedge/puppet-openvmtools/issues)?

**Comment by bshow80** [comment]
Done...sorry about that.
