### ISSUE TITLE
OEL 5.11, init.pp calls udevadm instead of udevcontrol

### ISSUE THREAD

**Issue by helperton** [razorsedge/puppet-vmwaretools#44]
The logic in the init.pp causes udevadm (which doesn't exist) to be called instead of udevcontrol on OEL 5.11 because you check for "operatingsystem == 'RedHat'" instead of perhaps a better option of "osfamily == 'RedHat'".

**Comment by razorsedge** [comment]
Fixed in razorsedge/vmwaretools version 6.0.0.
