### ISSUE TITLE
Fixes needed for STRICT_VARIABLES

### ISSUE THREAD

**Issue by alexjfisher** [razorsedge/puppet-vmwaretools#55]
The latest version of puppetlabs_spec_helper defaults `STRICT_VARIABLES=yes`.  (I'm not too sure why, but perhaps this will be the default or only setting when puppet 5 is released??)

`params.pp` references lots of top scope variables with the design being they might have come from an ENC.  With strict variables, if they're not set, catalog compilation will fail.  The solution is to use `getvar` from stdlib.  See https://blog.yo61.com/test-for-undefined-fact-in-puppet-with-strict_variables/

@razorsedge Is there also a typo here https://github.com/razorsedge/puppet-vmwaretools/blob/6.0.0/manifests/params.pp#L95 ?

**Comment by cdenneen** [comment]
This is the same as other https://github.com/razorsedge/puppet-snmp/pull/71

**Comment by razorsedge** [comment]
Fixed in #62 and released to the Forge as [6.1.0](https://forge.puppet.com/razorsedge/vmwaretools/6.1.0/).
