### ISSUE TITLE
Add support for RHEL 7 and CentOS 7

### ISSUE THREAD

**Issue by jzcmyz** [razorsedge/puppet-vmwaretools#58]
This is the error I get.

Notice: Scope(Class[Vmwaretools::Params]): Your operating system CentOS is unsupported and will not have the VMware Tools OSP installed.

**Comment by razorsedge** [comment]
VMware Tools is not available from VMware on RHEL/CentOS 7.  Thus this module does not support that OS.  Please use [razorsedge/openvmtools](https://forge.puppet.com/razorsedge/openvmtools) instead.
